[package]
name = "pren-core"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.9.5"
nom = "8.0.0"
tempfile = "3.22.0"
walkdir = "2.5.0"

[lib]
name = "pren_core"
path = "src/lib.rs"