[package]
name = "pren-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "pren"
path = "src/main.rs"

[dependencies]
pren-core = { path = "../pren-core"}
clap = { version = "4.5.47", features = ["derive"] }
clap_complete = "4.5.57"
arboard = "3.6.1"